require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'themall' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'ReactNativeAdsFacebook', :path => '../node_modules/react-native-fbads'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'FBAudienceNetwork'
  pod 'Google-Mobile-Ads-SDK'

  target 'themallTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'themall-tvOS' do
  # Pods for themall-tvOS

  target 'themall-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
